# SPDX-FileCopyrightText: © 2026 OpenCHAMI a Series of LF Projects, LLC
# SPDX-License-Identifier: MIT

name: govulncheck
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    uses: OpenCHAMI/github-actions/.github/workflows/govulncheck.yml@5b8f3decfae1c29ef4004a6f49f1593d25eccc95 # github-actions under test (seantronsen/feat/redesign-deployment)

  govulncheck:
    if: ${{ always() }}
    needs: [check]
    runs-on: ubuntu-slim
    steps:
      - uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with: { jobs: "${{ toJSON(needs) }}" }
